export const ApproverType = {
  CIVIL: 'CIVIL',
  BUILDING: 'BUILDING',
  STEEL_STRUCTURE: 'STEEL_STRUCTURE',
  MECHANICAL: 'MECHANICAL',
  PIPING: 'PIPING',
  ELECTRICAL: 'ELECTRICAL',
  INSTRUMENT: 'INSTRUMENT',
  PRECOM: 'PRECOM',
  PRESENTATIVE_SUBCON: 'PRESENTATIVE_SUBCON', // Deprecated
  PRESENTATIVE_SECL: 'PRESENTATIVE_SECL',
  STEEL_STRUCTURE_SUBCON: 'STEEL_STRUCTURE_SUBCON',
  AREA_SAFETY_SUBCON: 'AREA_SAFETY_SUBCON',
  HSE_SITE_IN_CHARGE: 'HSE_SITE_IN_CHARGE', // Deprecated
  PERMIT_ISSUER: 'PERMIT_ISSUER',
  PERMIT_COORDINATOR: 'PERMIT_COORDINATOR',
  PERMIT_RECEIVER: 'PERMIT_RECEIVER',
  OPERATOR: 'OPERATOR',
  RIGGER: 'RIGGER',
  SAFETY: 'SAFETY'
};
