import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'prismjs/themes/prism.css';
import { Flex } from 'antd';
import { HeaderV1 } from '@/containers';
import RQProvider from '@/app/RQProvider';
import StoreProvider from './StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <RQProvider>
            <Flex gap="middle" style={{ minHeight: '100vh' }}>
              <HeaderV1 />
              {children}
            </Flex>
          </RQProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
