import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import 'prismjs/themes/prism.css';
import StoreProvider from "./StoreProvider";
import { HeaderV1 } from "@/containers";
import { Flex } from "antd";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <Flex gap={'middle'} style={{ minHeight: '100vh' }}>
            <HeaderV1></HeaderV1>
            {children}

          </Flex>

        </body>
      </html>
    </StoreProvider>


  );
}
